name: Copy/Update Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the branch to copy'
        required: true
        type: string
      new_branch_name:
        description: 'Name for the new branch (optional, default is "copy-<target-branch-name>")'
        required: false
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Froggerpilot Repository
      uses: actions/checkout@v3
      with:
        repository: Froggerpilot/openpilot
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: FrogPilot

    - name: Extract Target Repo and Branch
      id: extract-info
      run: |
        echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV
        TARGET_URL=${{ github.event.inputs.target_url }}
        TARGET_REPO=$(echo $TARGET_URL | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
        TARGET_BRANCH=$(echo $TARGET_URL | sed -E 's|https://github.com/[^/]+/[^/]+/tree/(.+)|\1|')
        echo "TARGET_REPO=${TARGET_REPO}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
        echo "Target Repository: $TARGET_REPO"
        echo "Target Branch: $TARGET_BRANCH"

    - name: Generate Branch Name
      id: generate-branch-name
      run: |
        if [ -z "${{ github.event.inputs.new_branch_name }}" ]; then
          NEW_BRANCH_NAME="copy-${TARGET_BRANCH}"
        else
          NEW_BRANCH_NAME="${{ github.event.inputs.new_branch_name }}"
        fi
        echo "NEW_BRANCH_NAME=${NEW_BRANCH_NAME}" >> $GITHUB_ENV
        echo "New Branch Name: ${NEW_BRANCH_NAME}"

    - name: Clone External Repository
      run: |
        git clone https://github.com/${{ env.TARGET_REPO }} external-repo
        cd external-repo
        git checkout ${TARGET_BRANCH}
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}

    - name: Create and Push New Branch to Froggerpilot Repository
      run: |
        cd external-repo
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Froggerpilot/openpilot.git
        git fetch origin
        git checkout -b ${{ env.NEW_BRANCH_NAME }}  # Create a new branch in the local repo
        git push --force origin ${{ env.NEW_BRANCH_NAME }}  # Push the new branch to the remote
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_BRANCH_NAME: ${{ env.NEW_BRANCH_NAME }}
