name: Copy Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to copy'
        required: true
        type: string

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}

    - name: Extract target repo and branch
      id: extract
      run: |
        # Extract the repo and branch from the URL
        TARGET_URL="${{ github.event.inputs.target_url }}"
        REPO_URL=$(echo $TARGET_URL | sed 's/tree\/.*//')
        TARGET_BRANCH=$(echo $TARGET_URL | sed 's/.*tree\///')

        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV

    - name: Clone target repository
      run: |
        git clone $REPO_URL external-repo
        cd external-repo
        git fetch origin $TARGET_BRANCH
        git checkout -b $TARGET_BRANCH

    - name: Push to main repository
      run: |
        cd external-repo
        git remote add origin "https://github.com/Froggerpilot/openpilot.git"
        git push --force origin $TARGET_BRANCH
