on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the branch to copy'
        required: true
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Froggerpilot Repository
      uses: actions/checkout@v3
      with:
        repository: Froggerpilot/openpilot
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: FrogPilot

    - name: Extract Target Repo and Branch
      id: extract-info
      run: |
        echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV
        TARGET_URL=${{ github.event.inputs.target_url }}
        TARGET_REPO=$(echo $TARGET_URL | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
        TARGET_BRANCH=$(echo $TARGET_URL | sed -E 's|https://github.com/[^/]+/[^/]+/tree/(.+)|\1|')
        echo "TARGET_REPO=${TARGET_REPO}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
        echo "Target Repository: $TARGET_REPO"
        echo "Target Branch: $TARGET_BRANCH"
    - name: Clone External Repository
      run: |
        git clone https://github.com/${{ env.TARGET_REPO }} external-repo
        cd external-repo
        git checkout ${TARGET_BRANCH}
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}

    - name: Create and Push New Branch to Froggerpilot Repository
      run: |
        cd external-repo
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Froggerpilot/openpilot.git
        git fetch origin
        git checkout -b copy-${TARGET_BRANCH}  # Create a new branch in the local repo
        git push --force origin copy-${TARGET_BRANCH}  # Push the new branch to the remote
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
