name: Faster Copy/Update Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the branch to copy'
        required: true
        type: string
      new_branch_name:
        description: 'Name for the new branch (optional, default is "copy-<target-branch-name>")'
        required: false
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Froggerpilot Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.FROGGERPILOT_PAT }}
        repository: Froggerpilot/openpilot
        ref: FrogPilot
        fetch-depth: 1

    - name: Extract Target Repo and Branch
      id: extract-info
      run: |
        TARGET_URL=${{ github.event.inputs.target_url }}
        # Extract the target repository and branch from the URL
        TARGET_REPO=$(echo $TARGET_URL | cut -d'/' -f4,5)
        TARGET_BRANCH=$(echo $TARGET_URL | sed -E 's|.*/tree/(.*)|\1|')

        echo "TARGET_REPO=${TARGET_REPO}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
        echo "Target Repository: $TARGET_REPO"
        echo "Target Branch: $TARGET_BRANCH"

    - name: Generate Branch Name
      id: generate-branch-name
      run: |
        if [ -z "${{ github.event.inputs.new_branch_name }}" ]; then
          NEW_BRANCH_NAME="copy-${TARGET_BRANCH}"
        else
          NEW_BRANCH_NAME="${{ github.event.inputs.new_branch_name }}"
        fi
        echo "NEW_BRANCH_NAME=${NEW_BRANCH_NAME}" >> $GITHUB_ENV
        echo "New Branch Name: ${NEW_BRANCH_NAME}"

    - name: Clone the Target Repository
      run: |
        echo "Cloning target repository: ${{ env.TARGET_REPO }}"
        git clone https://github.com/${{ env.TARGET_REPO }} external-repo
        cd external-repo
        # Fetch the target branch directly
        git fetch origin ${TARGET_BRANCH}:${TARGET_BRANCH}
        git branch -r  # Show remote branches to verify it's fetched
        git checkout ${TARGET_BRANCH} || exit 1  # If branch does not exist, exit with an error
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}

    - name: Push the Branch to Your Repository
      run: |
        cd external-repo
        git remote set-url origin https://x-access-token:${{ secrets.FROGGERPILOT_PAT }}@github.com/Froggerpilot/openpilot.git
        git checkout -b ${{ env.NEW_BRANCH_NAME }}
        git push --set-upstream origin ${{ env.NEW_B
