name: Sync Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to sync from (e.g., https://github.com/garrettpall/openpilot/tree/frogpilot-gm-tune)'
        required: true
        type: string
      target_branch:
        description: 'Branch in your repo to sync with the target branch'
        required: true
        type: string

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch in your repo
        uses: actions/checkout@v3
        with:
          repository: 'Froggerpilot/openpilot'
          ref: ${{ github.event.inputs.target_branch }}

      - name: Clone target repository and branch
        run: |
          git clone ${GITHUB_EVENT_INPUTS_TARGET_URL} external-repo
          cd external-repo
          git checkout -b temp-sync-branch origin/$(basename ${GITHUB_EVENT_INPUTS_TARGET_URL})

      - name: Fetch and merge
        run: |
          cd external-repo
          git remote add your-repo https://github.com/Froggerpilot/openpilot.git
          git fetch your-repo
          git checkout temp-sync-branch
          git merge --strategy-option theirs your-repo/${{ github.event.inputs.target_branch }} || { echo "Merge conflicts detected, manual resolution required"; exit 1; }

      - name: Resolve conflicts (if any)
        run: |
          cd external-repo
          git status
          git diff --name-only --diff-filter=U
          echo "Conflicts need to be resolved manually if any files are listed."

      - name: Push changes to your repository
        run: |
          cd external-repo
          git push your-repo temp-sync-branch:${{ github.event.inputs.target_branch }} --force || exit 1

      - name: Clean up
        run: |
          rm -rf external-repo
