name: Sync Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to sync from (e.g., https://github.com/garrettpall/openpilot/tree/frogpilot-gm-tune)'
        required: true
        type: string
      target_branch:
        description: 'Branch in your repo to sync with the target branch'
        required: true
        type: string

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch in your repo
        uses: actions/checkout@v3
        with:
          repository: 'Froggerpilot/openpilot'
          ref: ${{ github.event.inputs.target_branch }}

      - name: Extract repository and branch from URL
        id: extract_info
        run: |
          TARGET_URL=${{ github.event.inputs.target_url }}
          echo "TARGET_URL=$TARGET_URL"
          REPO_URL=$(echo $TARGET_URL | sed -e 's|https://github.com/||' -e 's|/tree/.*||')
          BRANCH_NAME=$(echo $TARGET_URL | sed -e 's|.*tree/||')
          echo "REPO_URL=$REPO_URL"
          echo "BRANCH_NAME=$BRANCH_NAME"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Clone target repository and branch
        run: |
          git clone https://github.com/${{ env.REPO_URL }} external-repo
          cd external-repo
          git checkout -b temp-sync-branch origin/${{ env.BRANCH_NAME }}

      - name: Fetch and merge
        run: |
          cd external-repo
          git remote add your-repo https://github.com/Froggerpilot/openpilot.git
          git fetch your-repo
          git checkout temp-sync-branch
          git merge --strategy-option theirs your-repo/${{ github.event.inputs.target_branch }} || { echo "Merge conflicts detected, manual resolution required"; exit 1; }

      - name: Resolve conflicts (if any)
        run: |
          cd external-repo
          git status
          git diff --name-only --diff-filter=U
          echo "Conflicts need to be resolved manually if any files are listed."

      - name: Push changes to your repository
        run: |
          cd external-repo
          git push your-repo temp-sync-branch:${{ github.event.inputs.target_branch }} --force || exit 1

      - name: Clean up
        run: |
          rm -rf external-repo
