name: Sync Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to sync from'
        required: true
        type: string
      target_branch:
        description: 'Branch in your repo to sync with the target branch'
        required: true
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Froggerpilot Repository
        uses: actions/checkout@v3
        with:
          repository: Froggerpilot/openpilot
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.target_branch }}

      - name: Extract Target Repo and Branch
        id: extract-info
        run: |
          echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV
          
          TARGET_URL=${{ github.event.inputs.target_url }}
          TARGET_REPO=$(echo $TARGET_URL | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
          TARGET_BRANCH=$(echo $TARGET_URL | sed -E 's|https://github.com/[^/]+/[^/]+/tree/(.+)|\1|')
          echo "TARGET_REPO=${TARGET_REPO}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV

      - name: Clone the target repository
        run: |
          git clone https://github.com/${{ env.TARGET_REPO }} external-repo
          cd external-repo
          git fetch origin $TARGET_BRANCH
          git checkout -b temp-sync-branch origin/$TARGET_BRANCH || exit 1

      - name: Checkout the target branch in your repository
        run: |
          cd external-repo
          git remote add your-repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Froggerpilot/openpilot.git
          git fetch your-repo
          git checkout -b temp-local-sync your-repo/${{ github.event.inputs.target_branch }} || exit 1

      - name: Merge target branch into your branch
        run: |
          cd external-repo
          git checkout temp-local-sync
          git merge temp-sync-branch --no-edit || exit 1
          git push your-repo temp-local-sync:${{ github.event.inputs.target_branch }} --force || exit 1

      - name: Clean up
        run: |
          cd ..
          rm -rf external-repo
