name: Sync Branches

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to sync from'
        required: true
        type: string
      target_branch:
        description: 'Branch in your repo to sync with the target branch'
        required: true
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git user identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone the external repository
        run: |
          git clone ${{ github.event.inputs.target_url }} external-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch the target branch
        run: |
          cd external-repo
          git fetch origin ${{ github.event.inputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the target branch
        run: |
          cd external-repo
          git checkout -b temp-sync-branch origin/${{ github.event.inputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync target branch to your repository branch
        run: |
          cd external-repo
          git remote add your-repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Froggerpilot/openpilot.git
          git fetch your-repo ${{ github.event.inputs.target_branch }}
          git checkout -b temp-local-sync your-repo/${{ github.event.inputs.target_branch }}
          git merge temp-sync-branch
          git push your-repo temp-local-sync:${{ github.event.inputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          cd external-repo
          git remote remove your-repo
