name: Resync Branch

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the target branch to sync with'
        required: true
        type: string
      source_branch:
        description: 'Branch in the repository to update'
        required: true
        type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      with:
        repository: Froggerpilot/openpilot
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.inputs.source_branch }}

    - name: Extract Target Repo and Branch
      id: extract-info
      run: |
        echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV
        TARGET_URL=${{ github.event.inputs.target_url }}
        TARGET_REPO=$(echo $TARGET_URL | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
        TARGET_BRANCH=$(echo $TARGET_URL | sed -E 's|https://github.com/[^/]+/[^/]+/tree/(.+)|\1|')
        echo "TARGET_REPO=${TARGET_REPO}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
        echo "Target Repository: $TARGET_REPO"
        echo "Target Branch: $TARGET_BRANCH"

    - name: Clone External Repository
      run: |
        git clone https://github.com/${{ env.TARGET_REPO }} external-repo
        cd external-repo
        git checkout ${TARGET_BRANCH}
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}

    - name: Sync Branch with Target Branch
      run: |
        cd external-repo
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Froggerpilot/openpilot.git
        git fetch origin
        git checkout -b temp-sync-branch

        # Merge changes from target branch into temporary sync branch
        git pull origin ${TARGET_BRANCH}

        # Push the merged changes to the branch being updated
        cd ..
        git checkout ${GITHUB_REF#refs/heads/}
        git merge --no-ff external-repo/temp-sync-branch -m "Sync with ${TARGET_BRANCH} from ${TARGET_REPO}"
        git push --force

        # Clean up
        rm -rf external-repo
      env:
        TARGET_REPO: ${{ env.TARGET_REPO }}
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Display sync information
      run: |
        echo "Branch ${GITHUB_REF#refs/heads/} has been updated with changes from ${TARGET_BRANCH} in ${TARGET_REPO}."
